name: Node.js CI

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgres://lgjvxtqa:HIP0bscrm-56KBlSEXZbuCi6sPTIdQGf@bubble.db.elephantsql.com/lgjvxtqa

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          DATABASE_URL: postgres://lgjvxtqa:HIP0bscrm-56KBlSEXZbuCi6sPTIdQGf@bubble.db.elephantsql.com/lgjvxtqa

      # Additional steps for build, deployment, etc. can be added here